---
title: 'Lab 7: Data cleaning with dplyr'
subtitle: 'Practice Problems'
output:
  html_document:
    highlight: espresso
    theme: cerulean
---

# Basic 5 commands
## Practice
For this exercise, at each step use the assignment operator `<-` to store the results into a new data table and use that data in the next step. You will use the `hflights` data set which is data on  flights departing from two Houston airports in 2011. 

1. Use `select()` to extract the following variables:  `Distance`, and `AirTime`. 
2. Use `filter()` to select only the flights who traveled exactly 501 miles. 
3. Use `mutate()` to create a new variable `Speed` that calculates speed of the plane as Distance/AirTime*60.
4. Use `arrange()` to order the previous data frame by ascending `AirTime`. 
5. Use `slice()` to select the flight with the shortest time in the air. (_Hint: the shorteset flight should be in row 1 after you sort by ascending AirTime_). How fast did this plane go? 


# Additional Helper functions
## Practice
Still using the `hflights` data table, select columns with the following conditions: 

1. All varibles that start with the letter `D`.
2. All variables that end with `Num`.
3. All variables that contain an the word `Taxi` or `Delay`.  


# Chaining Operations
## Practice
Use dplyr functions and the pipe operator (` %>% `) to transform the following English sentences into R code:

1. Take the `hflights` data set and then ...
2. Add a variable named `diff` that is the result of subtracting `TaxiIn` from `TaxiOut`, and then ...
3. Pick all of the rows whose `diff` value does not equal `NA`, and then ...
4. Summarise the data set with a value named `avg` that is the mean diff value.  
5. Store the result in the variable `p`.

#### Challenge Question: Do you drive or fly? 
You can answer sophisticated questions by combining the verbs of dplyr. Now you will examine whether it sometimes makes sense to drive instead of fly. You will begin by making a data set that contains relevant variables. Then, you will find flights whose equivalent average velocity is lower than the velocity when traveling by car.

1. Define a data set named `d` that contains just the `Dest`, `UniqueCarrier`, `Distance`, and `ActualElapsedTime` columns of `hflights` as well as two additional variables: `RealTime` and `mph.RealTime` should be created as the actual elapsed time plus 100 minutes. This will be an estimate of how much time a person spends getting from point A to point B while flying, including getting to the airport, security checks, etc. mph will be the miles per hour that a person on the flight traveled based on the RealTime of the flight.


2. On many highways you can drive at 70 mph. Continue with `d` to calculate the following variables: 

* `n_less`, the number of flights whose mph value does not equal NA that traveled at less than 70 mph in real time
* `n_dest`, the number of destinations that were traveled to at less than 70 mph
* `min_dist`, the minimum distance of these flights
* `max_dist`, the maximum distance of these flights.
    
    
This suggests that some flights might be less efficient than driving in terms of speed. But is speed all that matters? Flying imposes burdens on a traveler that driving does not. For example, airplane tickets are very expensive. Air travelers also need to limit what they bring on their trip and arrange for a pick up or a drop off. Given these burdens we might demand that a flight provide a large speed advantage over driving.  

Let's define preferable flights as flights that are 150% faster than driving, i.e. that travel 105 mph or greater in real time. Also, assume that cancelled or diverted flights are less preferable than driving.

Write an adapted version of the solution to the previous exercise in an all-in-one fashion (i.e. in a single expression without 
intermediary variables, using %>%) to find:
  
* `n_non` - the number of non-preferable flights in hflights,
* `p_non` - the percentage of non-preferable flights in hflights,
* `n_dest` - the number of destinations that non-preferable flights traveled to,
* `min_dist` - the minimum distance that non-preferable flights traveled,
* `max_dist` - the maximum distance that non-preferable flights traveled.

To maintain readability in this advanced exercise, start your operations with a `select()` function to retain only the five columns that will be needed for the subsequent calculation steps.
